public class JenkinsTest{

  public static void test(){
    System.debug('Method called');
    System.debug('Method called');
    System.debug('Method called');
    System.debug('Method called');
    System.debug('Method called');
  }
  
  public static void test1(){
    System.debug('Method called');
    System.debug('Method called');
    System.debug('Method called');
    System.debug('Method called');
    System.debug('Method called');
  }
}
